[project]
name = "zip-recompress"
version = "0.0.1"
description = "Recompress zip file with new compression"
requires-python = ">=3.6"

[project.scripts]
zip-recompress = "zip-recompress:main"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["zip-recompress"]
package-dir = {"" = "src"}
